# Generated by Django 5.2.17 on 2026-08-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Aguardando pagamento'), ('PAID', 'Paga'), ('REFUSED', 'Pagamento recusado'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Prazo de pagamento esgotado')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
